# This workflow will do a clean install of node dependencies, build the source code 
# and run tests across different versions of node.  
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# FOLIO configurable env:
#   - YARN_TEST_OPTIONS
#   - SONAR_SRC_DIR


name: buildNPM Snapshot
on: 
  push:
    paths-ignore:
      - 'translations/**'
#  pull_request:
#     paths-ignore:
#      - 'translations/**'

jobs:
  Build:
    env:
      YARN_TEST_OPTIONS: ''
      FOLIO_NPM_REGISTRY: 'https://repository.folio.org/repository/npm-folioci/'
      NODEJS_VERSION: '12'

    runs-on: ubuntu-latest
    steps:
      - uses: folio-org/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          check-latest: true

      - run: yarn config set @folio:registry $FOLIO_NPM_REGISTRY

      - name: Set FOLIO NPM snapshot version
        run: | 
          git clone https://github.com/folio-org/folio-tools.git
          npm --no-git-tag-version version `folio-tools/github-actions-scripts/folioci_npmver.sh`
          rm -rf folio-tools
        env: 
          JOB_ID: ${{ github.run_number }}

      - name: Yarn install
        run: yarn install

      - name: Yarn list
        run: yarn list --pattern @folio

      - name: Yarn lint
        run: yarn lint
        continue-on-error: true

      - name: Yarn test
        run: xvfb-run --server-args="-screen 0 1024x768x24" yarn test:unit $YARN_TEST_OPTIONS 
        env:
          JEST_JUNIT_OUTPUT_DIR: 'artifacts/jest-junit'

      - name: Publish Jest unit test results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        if: always()
        with: 
          github_token: ${{ github.token }}
          files: artifacts/jest-unit/*.xml
 
      - name: Publish yarn.lock 
        uses: actions/upload-artifact@v2
        if: failure()
        with: 
          name: yarn.lock
          path: yarn.lock
          retention-days: 5
